---
abstract: 'type constraints for email addresses'
author:
  - 'André Walker <andre@andrewalker.net>'
build_requires:
  Test::More: '0'
  Test::TypeTiny: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Type-EmailAddress
provides:
  Type::EmailAddress:
    file: lib/Type/EmailAddress.pm
    version: '0.001'
requires:
  Email::Valid: '0'
  Type::Library: '0'
  Type::Utils: '0'
  Types::Standard: '0'
resources:
  bugtracker: https://github.com/andrewalker/p5-type-emailaddress/issues
  repository: git://github.com/andrewalker/p5-type-emailaddress.git
version: '0.001'
